# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-11-08 11:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', help_text='Your name', max_length=64, verbose_name='Name')),
                ('description', models.TextField(blank=True, default='', help_text='Enter your Blog.', verbose_name='Description')),
                ('city', models.TextField(blank=True, default='', help_text='Short title of the Blog.', verbose_name='Short Description')),
                ('images', models.ImageField(blank=True, upload_to='profile_image')),
                ('image1', models.ImageField(blank=True, upload_to='profile_image')),
                ('image2', models.ImageField(blank=True, upload_to='profile_image')),
                ('image3', models.ImageField(blank=True, upload_to='profile_image')),
                ('image4', models.ImageField(blank=True, upload_to='profile_image')),
                ('DOB', models.DateField(blank=True, default='', help_text='date of birth.', verbose_name='data of brith ')),
                ('webpage', models.TextField(blank=True, default='', help_text='URL of your webpage.', verbose_name='URL of your website')),
                ('organization', models.CharField(blank=True, default='', help_text='name of organization.', max_length=64, verbose_name='name of organization')),
                ('skills', models.TextField(blank=True, default='', help_text='list of skills.', verbose_name='list of skills')),
                ('location', models.CharField(blank=True, default='', help_text='your location.', max_length=64, verbose_name='your location')),
                ('phonenumber', models.CharField(blank=True, default='', help_text='enter your phone number ', max_length=64, verbose_name='Enter your phone number')),
                ('price', models.IntegerField(blank=True, default='', help_text='enter your hourly price in $', verbose_name='enter the price ')),
                ('contact_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='When this person completed the contact form.', verbose_name='contact date')),
                ('was_contacted', models.BooleanField(default=False, help_text='Check this if someone has already reached out to this person.', verbose_name='has been contacted?')),
                ('notes', models.TextField(blank=True, default='', help_text='Internal notes relating to contacting this person.', verbose_name='contact notes')),
                ('referer', models.CharField(blank=True, default='', help_text='This is the page the visitor was on before coming to the contact page.', max_length=2048, verbose_name='referring page')),
            ],
        ),
        migrations.CreateModel(
            name='ProfilePluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='profile_profilepluginmodel', serialize=False, to='cms.CMSPlugin')),
                ('title', models.CharField(blank=True, help_text='Optional. Title of the widget.', max_length=64, verbose_name='title')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
