# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-11-08 11:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='image1',
            new_name='fourthimage',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='image2',
            new_name='profileimage',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='image3',
            new_name='secondimage',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='image4',
            new_name='thirdimage',
        ),
    ]
