# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-02-04 13:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profile', '0002_auto_20181108_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='fourthimage',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='images',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='secondimage',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='thirdimage',
        ),
        migrations.AddField(
            model_name='profile',
            name='account',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='samplework1',
            field=models.ImageField(blank=True, help_text='Upload your sample work.', upload_to='profile_image'),
        ),
        migrations.AddField(
            model_name='profile',
            name='samplework2',
            field=models.ImageField(blank=True, help_text='Upload your sample work.', upload_to='profile_image'),
        ),
        migrations.AddField(
            model_name='profile',
            name='samplework3',
            field=models.ImageField(blank=True, help_text='Upload your sample work.', upload_to='profile_image'),
        ),
        migrations.AddField(
            model_name='profile',
            name='samplework4',
            field=models.ImageField(blank=True, help_text='Upload your sample work.', upload_to='profile_image'),
        ),
    ]
