# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-03-07 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0003_auto_20190204_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='DOB',
            field=models.DateField(default='', help_text='date of birth.', verbose_name='data of brith '),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.TextField(default='', help_text='Short title of the Blog.', verbose_name='Short Description'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(default='', help_text='Enter your Blog.', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(default='', help_text='your location.', max_length=64, verbose_name='your location'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(default='', help_text='Your name', max_length=64, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='organization',
            field=models.CharField(default='', help_text='name of organization.', max_length=64, verbose_name='name of organization'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phonenumber',
            field=models.CharField(default='', help_text='enter your phone number ', max_length=64, verbose_name='Enter your phone number'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='price',
            field=models.IntegerField(default='', help_text='enter your hourly price in $', verbose_name='enter the price '),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profileimage',
            field=models.ImageField(upload_to='profile_image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='samplework1',
            field=models.ImageField(help_text='Upload your sample work.', upload_to='profile_image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='samplework2',
            field=models.ImageField(help_text='Upload your sample work.', upload_to='profile_image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='samplework3',
            field=models.ImageField(help_text='Upload your sample work.', upload_to='profile_image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='samplework4',
            field=models.ImageField(help_text='Upload your sample work.', upload_to='profile_image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skills',
            field=models.TextField(default='', help_text='list of skills.', verbose_name='list of skills'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='webpage',
            field=models.TextField(default='', help_text='URL of your webpage.', verbose_name='URL of your website'),
        ),
    ]
