# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-27 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='images',
            field=models.ImageField(blank=True, upload_to='blog_image'),
        ),
    ]
