# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-11 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogging', '0002_blogs_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='images',
            field=models.ImageField(blank=True, default='workdir/polymorphic/media/blog_image/download.jpeg', upload_to='blog_image'),
        ),
    ]
