# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-11 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogging', '0003_auto_20181011_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='images',
            field=models.ImageField(blank=True, default='blog_image/black.png', upload_to='blog_image'),
        ),
    ]
