# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-19 13:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
        ('shop', '0009_videoplayer_videosource_videotrack'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoplayer',
            name='cmsplugin_ptr',
        ),
        migrations.RemoveField(
            model_name='videoplayer',
            name='poster',
        ),
        migrations.RemoveField(
            model_name='videosource',
            name='cmsplugin_ptr',
        ),
        migrations.RemoveField(
            model_name='videosource',
            name='source_file',
        ),
        migrations.RemoveField(
            model_name='videotrack',
            name='cmsplugin_ptr',
        ),
        migrations.RemoveField(
            model_name='videotrack',
            name='src',
        ),
        migrations.DeleteModel(
            name='VideoPlayer',
        ),
        migrations.DeleteModel(
            name='VideoSource',
        ),
        migrations.DeleteModel(
            name='VideoTrack',
        ),
    ]
