# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-31 11:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
        ('myshop', '0003_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='myshop_blogpluginmodel', serialize=False, to='cms.CMSPlugin')),
                ('title', models.CharField(blank=True, help_text='Optional. Title of the widget.', max_length=64, verbose_name='title')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.AddField(
            model_name='blog',
            name='Description',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
