# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-11-08 11:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
        ('myshop', '0004_auto_20180831_1312'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.RemoveField(
            model_name='blogpluginmodel',
            name='cmsplugin_ptr',
        ),
        migrations.DeleteModel(
            name='BlogPluginModel',
        ),
    ]
