# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-06-17 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0003_auto_20190514_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='hire',
            name='end_date',
            field=models.DateTimeField(help_text='You need to ad the time when your payment will be transfered to freelancer account', null=True, verbose_name='when will your event end'),
        ),
    ]
