# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-02-04 13:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('email_auth', '0005_auto_20190204_1403'),
        ('profile', '0003_auto_20190204_1403'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobbid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='date published')),
                ('price', models.IntegerField(blank=True, default='', help_text='enter your offer price $')),
                ('Details', models.CharField(max_length=200)),
                ('Yourprofile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profile.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, default='', help_text='Your name', max_length=64, verbose_name='Name')),
                ('title', models.TextField(blank=True, default='', help_text='what kind of skills you are looking for.', verbose_name='skills')),
                ('images', models.ImageField(blank=True, upload_to='profile_image')),
                ('date', models.DateField(blank=True, default='', help_text='enter the date of project.', verbose_name='enter the date when you want it  ')),
                ('description', models.TextField(blank=True, default='', help_text='enter the description of job.', verbose_name='Enter the description')),
                ('location', models.CharField(blank=True, default='', help_text='your location.', max_length=64, verbose_name='your location')),
                ('price', models.IntegerField(blank=True, default='', help_text='enter your hourly price willing to pay in $', verbose_name='enter the price you willing to pay ')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileJob',
            fields=[
                ('name', models.CharField(blank=True, default='', help_text='Your name', max_length=64, verbose_name='Name')),
                ('aboutyou', models.TextField(blank=True, default='', help_text='About you.', verbose_name='About you')),
                ('profileimage', models.ImageField(blank=True, upload_to='profile_image')),
                ('location', models.CharField(blank=True, default='', help_text='your location.', max_length=64, verbose_name='your location')),
                ('address', models.CharField(blank=True, default='', help_text='enter your phone number ', max_length=64, verbose_name='Enter your phone number')),
                ('account', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('contact_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='When this person completed the contact form.', verbose_name='contact date')),
                ('was_contacted', models.BooleanField(default=False, help_text='Check this if someone has already reached out to this person.', verbose_name='has been contacted?')),
                ('notes', models.TextField(blank=True, default='', help_text='Internal notes relating to contacting this person.', verbose_name='contact notes')),
                ('referer', models.CharField(blank=True, default='', help_text='This is the page the visitor was on before coming to the contact page.', max_length=2048, verbose_name='referring page')),
            ],
        ),
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.AddField(
            model_name='jobs',
            name='jobprofile',
            field=models.ManyToManyField(to='jobs.ProfileJob'),
        ),
        migrations.AddField(
            model_name='jobbid',
            name='jobappliedto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.Jobs'),
        ),
    ]
