# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-02-04 13:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20190204_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='jobprofile',
        ),
        migrations.AddField(
            model_name='jobs',
            name='jobprofile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.ProfileJob'),
        ),
    ]
