# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-03-07 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20190204_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='date',
            field=models.DateField(default='', help_text='enter the date of project.', verbose_name='enter the date when you want it  '),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='description',
            field=models.TextField(default='', help_text='enter the description of job.', verbose_name='Enter the description'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='images',
            field=models.ImageField(upload_to='profile_image'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='location',
            field=models.CharField(default='', help_text='your location.', max_length=64, verbose_name='your location'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='price',
            field=models.IntegerField(default='', help_text='enter your hourly price willing to pay in $', verbose_name='enter the price you willing to pay '),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='title',
            field=models.TextField(default='', help_text='what kind of skills you are looking for.', verbose_name='skills'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='type',
            field=models.CharField(default='', help_text='Your name', max_length=64, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='profilejob',
            name='aboutyou',
            field=models.TextField(default='', help_text='About you.', verbose_name='About you'),
        ),
        migrations.AlterField(
            model_name='profilejob',
            name='address',
            field=models.CharField(default='', help_text='enter your phone number ', max_length=64, verbose_name='Enter your phone number'),
        ),
        migrations.AlterField(
            model_name='profilejob',
            name='location',
            field=models.CharField(default='', help_text='your location.', max_length=64, verbose_name='your location'),
        ),
        migrations.AlterField(
            model_name='profilejob',
            name='name',
            field=models.CharField(default='', help_text='Your name', max_length=64, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='profilejob',
            name='profileimage',
            field=models.ImageField(upload_to='profile_image'),
        ),
    ]
